SET SERVEROUTPUT ON SIZE UNLIMITED;  

SELECT LTRIM('ABCDE', 'ABC')
        , RTRIM('ABCDE', 'EDCB')
    FROM DUAL;

-- LPAD, RPAD
CREATE TABLE EX4_1 (
    PHONE_NUM VARCHAR2(30)
);

INSERT INTO EX4_1 VALUES ('111-1111');
INSERT INTO EX4_1 VALUES ('111-2222');
INSERT INTO EX4_1 VALUES ('111-3333');

SELECT * FROM EX4_1;

SELECT LPAD(PHONE_NUM, 12, '(02)') FROM EX4_1;

SELECT RPAD(PHONE_NUM, 12, '(02)') FROM EX4_1;

-- REPLACE, TRANSLATE
SELECT REPLACE('나는 너를 모르는데 너는 나를 알겠는가?', '나', '너') FROM DUAL;

SELECT REPLACE('나는 너를 모르는데 너는 나를 알겠는가', '나는', '너를') AS REP,
        TRANSLATE('나는 너를 모르는데 너는 나를 알겠는가', '나는', '너를') AS TRN
    FROM DUAL;

-- SYSDATE, SYSTIMESTAMP
SELECT SYSDATE, SYSTIMESTAMP FROM DUAL;

-- TO_CHAR
SELECT TO_CHAR(123456789, '999,999,999') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DDD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'WW') FROM DUAL;

-- NVL, NVL2
SELECT NVL(MANAGER_ID, EMPLOYEE_ID)
    FROM EMPLOYEES E
    WHERE E.MANAGER_ID IS NULL;

-- COALESCE
SELECT EMPLOYEE_ID, SALARY, COMMISSION_PCT,
        COALESCE(SALARY * COMMISSION_PCT, SALARY) AS SALARY2
    FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;

-- LNNVL
SELECT E.EMPLOYEE_ID, E.COMMISSION_PCT
    FROM EMPLOYEES E
    WHERE E.COMMISSION_PCT < 0.2;

SELECT COUNT(*) FROM EMPLOYEES E
    WHERE NVL(COMMISSION_PCT, 0) < 0.2;

SELECT COUNT(*)
    FROM EMPLOYEES E
    WHERE LNNVL(E.COMMISSION_PCT >= 0.2);

