-- FLOAT TYPE형 오류 생성 : FLOAT(n)에서 n은 2진수 기준
CREATE TABLE FLOAT_ERR_2_4 (
    FLOAT_COL1 FLOAT(38),
    FLOAT_COL2 FLOAT
);

DROP TABLE FLOAT_ERR_2_4;

INSERT INTO FLOAT_ERR_2_4(FLOAT_COL1, FLOAT_COL2)
    VALUES (1234567891234, 1234567891234);

SELECT * FROM FLOAT_ERR_2_4;


-- DATA와 TIMESTAMP : 날짜형 DATA TYPE 구분
CREATE TABLE DATA_TYPE_2_5 (
    COL_DATE    DATE,
    COL_TIMESTAMP   TIMESTAMP
);

INSERT INTO DATA_TYPE_2_5
    VALUES(SYSDATE, SYSDATE);

INSERT INTO DATA_TYPE_2_5
    VALUES(SYSDATE, SYSTIMESTAMP);

SELECT * FROM DATA_TYPE_2_5;
COMMIT;
ROLLBACK;
