
-- 패키지 명세 확인(USER_SOURCE 확인)
SELECT TEXT
    FROM USER_SOURCE
    WHERE TYPE = 'PACKAGE'
    AND NAME = 'PKG_EXAMPLE'
    ;

-- PACKAGE 명세 확인
DESC PKG_EXAMPLE;


-- 패키지 SPECIFICATION(명세)
CREATE OR REPLACE PACKAGE PKG_EXAMPLE
IS
    SPEC_NO NUMBER := 10;
    FUNCTION FUNC_AFTERTAX(SAL NUMBER) RETURN NUMBER;
    PROCEDURE PRO_EMP(IN_EMPNO IN EMP.EMPNO%TYPE);
    PROCEDURE PRO_DEPT(IN_DEPTNO IN DEPT.DEPTNO%TYPE);
END;
/

-- PACKAGE 본문 작성
CREATE OR REPLACE PACKAGE BODY PKG_EXAMPLE
IS
    BODY_NO NUMBER := 10;

    FUNCTION FUNC_AFTERTAX(SAL NUMBER) 
        RETURN NUMBER
        IS
            TAX NUMBER := 0.05;

        BEGIN
            RETURN (ROUND(SAL - (SAL * TAX)));

    END FUNC_AFTERTAX;

    PROCEDURE PRO_EMP(IN_EMPNO IN EMP.EMPNO%TYPE)
        IS 
            OUT_ENAME EMP.ENAME%TYPE;
            OUT_SAL EMP.SAL%TYPE;
        
        BEGIN
            SELECT ENAME, SAL 
                INTO OUT_ENAME, OUT_SAL
                FROM EMP
                WHERE EMPNO = IN_EMPNO;

            DBMS_OUTPUT.PUT_LINE('ENAME : ' || OUT_ENAME);
            DBMS_OUTPUT.PUT_LINE('SAL : ' || OUT_SAL);

    END PRO_EMP;

    PROCEDURE PRO_DEPT(IN_DEPTNO IN DEPT.DEPTNO%TYPE)
        IS
            OUT_DNAME DEPT.DNAME%TYPE;
            OUT_LOC DEPT.LOC%TYPE;
        
        BEGIN
            SELECT DNAME, LOC
                INTO OUT_DNAME, OUT_LOC
                FROM DEPT
                WHERE DEPTNO = IN_DEPTNO;
            
            DBMS_OUTPUT.PUT_LINE('DNAME : ' || OUT_DNAME);
            DBMS_OUTPUT.PUT_LINE('LOC : ' || OUT_LOC);
    
    END PRO_DEPT;
END;
/


-- PACKAGE OVERLOAD 작성
CREATE OR REPLACE PACKAGE PKG_OVERLOAD
IS
    PROCEDURE PRO_EMP(IN_EMPNO IN EMP.EMPNO%TYPE);
    PROCEDURE PRO_EMP(IN_ENAME IN EMP.ENAME%TYPE);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_OVERLOAD
IS
    PROCEDURE PRO_EMP(IN_EMPNO IN EMP.EMPNO%TYPE)
        IS
            OUT_ENAME EMP.ENAME%TYPE;
            OUT_SAL EMP.SAL%TYPE;
        
        BEGIN
            SELECT ENAME, SAL
            INTO OUT_ENAME, OUT_SAL
            FROM EMP
            WHERE EMPNO = IN_EMPNO;

            DBMS_OUTPUT.PUT_LINE('ENAME : ' || OUT_ENAME);
            DBMS_OUTPUT.PUT_LINE('SAL : ' || OUT_SAL);
    END PRO_EMP;

    PROCEDURE PRO_EMP(IN_ENAME IN EMP.ENAME%TYPE)
        IS 
            OUT_ENAME EMP.ENAME%TYPE;
            OUT_SAL EMP.SAL%TYPE;
        
        BEGIN
            SELECT ENAME, SAL
            INTO OUT_ENAME, OUT_SAL
            FROM EMP
            WHERE ENAME = IN_ENAME;

            DBMS_OUTPUT.PUT_LINE('ENAME : ' || OUT_ENAME);
            DBMS_OUTPUT.PUT_LINE('SAL : ' || OUT_SAL);
        END PRO_EMP;
END;
/

SELECT * FROM USER_SOURCE A
WHERE A.NAME = 'PKG_OVERLOAD';
