-- FLOAT TYPE형 오류 생성 : FLOAT(n)에서 n은 2진수 기준
CREATE TABLE FLOAT_ERR_2_4 (
    FLOAT_COL1 FLOAT(38),
    FLOAT_COL2 FLOAT
);

DROP TABLE FLOAT_ERR_2_4;

INSERT INTO FLOAT_ERR_2_4(FLOAT_COL1, FLOAT_COL2)
    VALUES (1234567891234, 1234567891234);

SELECT * FROM FLOAT_ERR_2_4;


-- DATA와 TIMESTAMP : 날짜형 DATA TYPE 구분
CREATE TABLE DATA_TYPE_2_5 (
    COL_DATE        DATE,
    COL_TIMESTAMP   TIMESTAMP
);

-- INTERVAL (DAY/YEAR{일/년에 대한 자릿수}) TO (SECOND/MONTH{초/월에 대한 자릿수})
ALTER TABLE DATA_TYPE_2_5 ADD (COL_INTER_01 INTERVAL DAY(3) TO SECOND);
UPDATE DATA_TYPE_2_5 SET COL_DATE = (COL_DATE + COL_INTER_01) WHERE COL_DATE = 14/04/25;
-- TIMESTAMP WITH TIME ZONE 

-- TIMESTAMP WITH LOCAL TIMEZONE

INSERT INTO DATA_TYPE_2_5
    VALUES(SYSDATE, SYSDATE, INTERVAL '3 00:00:00' DAY TO SECOND);

INSERT INTO DATA_TYPE_2_5
    VALUES(SYSDATE, SYSTIMESTAMP);
    
    UPDATE DATA_TYPE_2_5 
SET COL_INTER_01 = INTERVAL '3 00:00:00' DAY TO SECOND;

ALTER TABLE DATA_TYPE_2_5 DROP COLUMN COL_INTER_01;
ALTER TABLE DATA_TYPE_2_5 ADD (COL_INTER_01_NEW INTERVAL DAY(3) TO SECOND(0));
UPDATE DATA_TYPE_2_5 SET COL_INTER_01 = COL_DATE + INTERVAL DAY(3) TO SECOND(0);

ALTER TABLE DATA_TYPE_2_5 RENAME COLUMN COL_INTER_01_NEW TO COL_INTER_01;
SELECT * FROM DATA_TYPE_2_5;
DESC DATA_TYPE_2_5; 
COMMIT;
ROLLBACK;


/**
LOB DATA TYPE

CLOB    - 고정길이, 가변길이 문자 집합 지원, 문자형 대용량 객체
NCLOB   - 유니코드를 포함한 문자형 대용량 객체
BLOB    - 이진형 대용량 객체(그래픽, 이미지, 동영상 등의 데이터)
BFILE   - 대용량 이진 파일에 대한 로케이터 저장(파일이 아닌 파일의 위치를 가리키는 포인터, 읽기 작업만 가능)

RAW         - 
LONG RAW    - 
ROWID       - 
UROWID      - 

*/
