
-- PROCEDURE ERROR 내기
SET SERVEROUTPUT ON SIZE UNLIMITED;  
CREATE OR REPLACE PROCEDURE PRO_ERR

IS
    ERR_NO NUMBER;

BEGIN
    ERR_NO = 100;
    DBMS_OUTPUT.PUT_LINE('ERR_NO : ' || ERR_NO);
END PRO_ERR;
/

-- USER_ERRORS로 오류 확인하기
SHOW ERRORS; -- VSCODE에서 안보임

SHOW ERR PROCEDURE PRO_ERR;

SELECT * 
    FROM USER_ERRORS
    WHERE NAME = 'PRO_ERR';


-- 2. 급여 값을 받아서 세금을 제하고 실수령액을 계산해보기
CREATE OR REPLACE FUNCTION FUNC_AFTERTAX (
    SAL IN NUMBER
)
RETURN NUMBER

IS
    TAX NUMBER := 0.05;

BEGIN
    RETURN (ROUND(SAL - (SAL * TAX)));
END FUNC_AFTERTAX;
/

-- 2.1 PL/SQL에서 함수 사용
DECLARE
    AFTERTAX NUMBER;
    
BEGIN
    AFTERTAX := FUNC_AFTERTAX(3000);
    DBMS_OUTPUT.PUT_LINE('AFTER-TAX INCOME : ' || AFTERTAX);
END;
/

-- 2.2 SQL에서 함수 사용
SELECT FUNC_AFTERTAX(3000)
    FROM DUAL;

-- 2.3 함수에 테이블 데이터 사용하기
SELECT E.EMPNO, E.ENAME, E.SAL, 
        FUNC_AFTERTAX(E.SAL) AS AFTERTAX
    FROM EMP E;

-- DROP 함수 삭제해보기
DROP FUNCTION FUNC_AFTERTAX;

