
-- 컬랙션 메서드 사용하기
SET SERVEROUTPUT ON SIZE UNLIMITED;
DECLARE
    TYPE ITAB_EX IS TABLE OF VARCHAR2(20)
INDEX BY PLS_INTEGER;

    TEXT_ARR ITAB_EX;

BEGIN
    TEXT_ARR(1) := '1st data';
    TEXT_ARR(2) := '2nd data';
    TEXT_ARR(3) := '3rd data';
    TEXT_ARR(50) := '50th data';

    DBMS_OUTPUT.PUT_LINE('text_arr.COUNT : ' || text_arr.COUNT);
    DBMS_OUTPUT.PUT_LINE('text_arr.FIRST : ' || text_arr.FIRST);
    DBMS_OUTPUT.PUT_LINE('text_arr.LAST : ' || text_arr.LAST);
    DBMS_OUTPUT.PUT_LINE('text_arr.PRIOR(50) : ' || text_arr.PRIOR(50));
    DBMS_OUTPUT.PUT_LINE('text_arr.NEXT(50) : ' || text_arr.NEXT(50));

END;
/

CREATE TABLE EMP_RECORD AS SELECT * FROM EMP WHERE 1=2;
SELECT * FROM EMP_RECORD;

DESC EMP_RECORD;


-- EMP TABLE과 같은 구조를 가져서 EMP에 DATA를 넣을 수 있는 빈 테이블 EMP_RECORD
SET SERVEROUTPUT ON SIZE UNLIMITED;
DECLARE
    TYPE REC_EMP IS RECORD(
        EMPNO EMP.EMPNO%TYPE,
        ENAME EMP.ENAME%TYPE,
        JOB EMP.JOB%TYPE,
        MGR EMP.MGR%TYPE,
        HIREDATE EMP.HIREDATE%TYPE,
        SAL EMP.SAL%TYPE,
        COMM EMP.COMM%TYPE,
        DEPTNO EMP.DEPTNO%TYPE
    );

    EMP_REC REC_EMP;
BEGIN

    EMP_REC.EMPNO := 1111;
    EMP_REC.ENAME := 'TEST_USER';
    EMP_REC.JOB := 'TEST_JOB';
    EMP_REC.MGR := '18';
    EMP_REC.HIREDATE := TO_DATE('2018-03-01', 'YYYY-MM-DD');
    EMP_REC.SAL := 3000;
    EMP_REC.COMM := 0;
    EMP_REC.DEPTNO := 40;

    INSERT INTO EMP_RECORD
        VALUES EMP_REC;
END;
/


