SELECT * 
  FROM ALL_USERS
 WHERE USERNAME = 'SCOTT'
;

SELECT TABLE_NAME 
  FROM ALL_TABLES
 WHERE TABLE_NAME = 'EMP'
;

SELECT *
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'DEPT'
;

SELECT E.* FROM SCOTT.EMP E;
SELECT * FROM SCOTT.DEPT;
SELECT * FROM SCOTT.SALGRADE;
SELECT * FROM SCOTT.JOBS;

-- 중복되는 이름의 테이블 조회
SELECT * FROM USER_SYNONYMS WHERE SYNONYM_NAME = 'EMP';

--권한 부여
GRANT SELECT ON SCOTT.EMP TO PUBLIC;

show user;

