SELECT E.ENAME
        ,E.SAL
        ,E.SAL * 12 + E.COMM AS ANNSAL
        ,COMM
FROM SCOTT.EMP E
;

SELECT DISTINCT E.JOB
FROM SCOTT.EMP E
;

SELECT E.EMPNO AS EMPLOYEE_NO
        ,E.ENAME AS EMPLOYEE_NAME
        ,E.MGR AS MANAGER
        ,E.SAL AS SALARY
        ,E.COMM AS COMMISSION
        ,E.DEPTNO AS DEPARTMENT_NO
FROM SCOTT.EMP E
ORDER BY E.EMPNO DESC
        ,E.ENAME ASC
;

SELECT E.*
FROM EMP E
WHERE E.EMPNO = 7782
;

SELECT E.*
FROM EMP E
WHERE 1=1 
AND E.ENAME >= 'F'
;

SELECT E.*
FROM EMP E
WHERE NOT E.SAL = 3000
;

SELECT E.*
FROM EMP E
WHERE E.JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK')
;

SELECT *
FROM SOME_TABLE 
WHERE SOME_COLUMN LIKE 'A|_A%' ESCAPE '|'
;

SELECT E.EMPNO
        ,E.ENAME
        ,E.SAL
        ,E.DEPTNO
FROM EMP E
WHERE E.DEPTNO = 10
UNION
SELECT M.EMPNO
        ,M.ENAME
        ,M.SAL
        ,M.DEPTNO
FROM EMP M
WHERE M.DEPTNO = 20
;

show user;