SELECT E.* FROM SCOTT.EMP E WHERE E.ENAME LIKE '%S';

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, E.DEPTNO
FROM SCOTT.EMP E 
WHERE E.DEPTNO = 30 
AND E.JOB = 'SALESMAN'
;

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, E.DEPTNO
FROM SCOTT.EMP E
WHERE E.DEPTNO  = 20
AND E.SAL > 2000
UNION
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, E.DEPTNO
FROM SCOTT.EMP E
WHERE E.DEPTNO  = 30
AND E.SAL > 2000
;

SELECT E.* 
FROM SCOTT.EMP E
WHERE E.SAL >= 2000 AND E.SAL <= 3000
;

SELECT E.*
FROM SCOTT.EMP E
WHERE E.JOB IN ('CLERK', 'MANAGER')
AND E.MGR IS NOT NULL
AND E.ENAME NOT LIKE '_L%'
;

SELECT E.ENAME, UPPER(E.ENAME), LOWER(E.ENAME), INITCAP(E.ENAME)
FROM SCOTT.EMP E
;

SELECT E.*
FROM SCOTT.EMP E
WHERE UPPER(E.ENAME) = UPPER('jones')
;

SELECT E.ENAME, LENGTH(E.ENAME)
FROM EMP E
;

SELECT E.ENAME, LENGTH(E.ENAME)
FROM EMP E
WHERE LENGTH(E.ENAME) >= 5
;

SELECT E.JOB, SUBSTR(E.JOB, 1, 2), SUBSTR(E.JOB, 3, 2), SUBSTR(E.JOB, 5)
FROM EMP E
;

SELECT E.JOB, 
        SUBSTR(E.JOB, -LENGTH(E.JOB)),
        SUBSTR(E.JOB, -LENGTH(E.JOB), 2),
        SUBSTR(E.JOB, -3)
FROM EMP E
;

SELECT INSTR('HELLO, ORACLE!', 'L') AS INSTR_1,
        INSTR('HELLO, ORACLE!', 'L', 5) AS INSTR_2,
        INSTR('HELLO, ORACLE!', 'L', 2, 2) AS INSTR_3
FROM DUAL
;

SELECT E.*
FROM EMP E
WHERE INSTR(E.ENAME, 'S') > 0
;

SELECT '010-1234-5678' AS REPLACE_BEFORE,
        REPLACE('010-1234-5678', '-', '') AS REPLACE_1,
        REPLACE('010-1234-5678', '-') AS REPLACE_2
FROM DUAL
;

SELECT 'Oracle',
        LPAD('Oracle', 10, '#') AS LPAD_1,
        RPAD('Oracle', 10, '*') AS RPAD_1,
        LPAD('Oracle', 10) AS LPAD_2,
        RPAD('Oracle', 10) AS RPAD_2
FROM DUAL
;        

SELECT RPAD('991226-', 14, '*') AS PRAD_HMNO,  
        RPAD('010-4162-', 13, '*') AS RPAD_PHONE
FROM DUAL
;

select table_name from user_tables;