SELECT E.EMPNO, E.ENAME, E.EMPNO + '500'
    FROM EMP E
    WHERE E.ENAME = 'SMITH'
;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS DATE_A
    FROM DUAL
;

SELECT SYSDATE,
        TO_CHAR(SYSDATE, 'MM') AS MM,
        TO_CHAR(SYSDATE, 'MON') AS MON,
        TO_CHAR(SYSDATE, 'CC') AS CC,
        TO_CHAR(SYSDATE, 'DD') AS DD,
        TO_CHAR(SYSDATE, 'DY') AS DY,
        TO_CHAR(SYSDATE, 'DAY') AS DAY,
        TO_CHAR(SYSDATE, 'YY') AS YY,
        TO_CHAR(SYSDATE, 'W') AS W
    FROM DUAL
;

SELECT SYSDATE,
        TO_CHAR(SYSDATE, 'HH24:MI:SS') AS HH24MISS,
        TO_CHAR(SYSDATE, 'HH12:MI:SS AM') AS HHMISS_AM,
        TO_CHAR(SYSDATE, 'HH12:MI:SS P.M.') AS HHMISS_PM
    FROM DUAL
;

SELECT TO_NUMBER('1,300', '999,999') - TO_NUMBER('1,500', '999,999')
        FROM DUAL
;

SELECT TO_DATE('2018-09-29', 'YYYY-MM-DD') AS TODATE1,
        TO_DATE('20180929', 'YYYY-MM-DD') AS TODATE2
    FROM DUAL
;

SELECT E.*
    FROM EMP E
    WHERE E.HIREDATE > TO_DATE('1981/06/01', 'YYYY/MM/DD')
;

SELECT E.EMPNO, E.ENAME, E.SAL, E.COMM, E.SAL + E.COMM,
        NVL(E.COMM, 0),
        E.SAL + NVL(E.COMM, 0)
    FROM EMP E
;

SELECT E.EMPNO, E.ENAME, E.COMM,
        NVL2(E.COMM, 'O', 'X'),
        NVL2(E.COMM, SAL * 12 + E.COMM, E.SAL * 12) AS ANNSAL
    FROM EMP E
;

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL,
        DECODE(E.JOB,
                    'MANAGE', E.SAL * 1.1,
                    'SALESMAN', E.SAL * 1.05,
                    'ANALYST', E.SAL,
                    E.SAL * 1.03) AS UPSAL
    FROM EMP E
;

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL,
        CASE E.JOB
            WHEN 'MANAGE' THEN E.SAL * 1.1
            WHEN 'SALESMAN' THEN E.SAL * 1.05
            WHEN 'ANALYST' THEN E.SAL
            ELSE E.SAL * 1.03
        END AS UPSAL
    FROM EMP E
;

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL,
        CASE
            WHEN E.COMM IS NULL THEN 'X'
            WHEN E.COMM = 0 THEN 'O'
            WHEN E.COMM > 0 THEN 'OVER!!'
        END AS COMM_TEXT
    FROM EMP E
;

SELECT E.EMPNO,
        CONCAT(TO_CHAR(SUBSTR(E.EMPNO, 1, 2)), '**') AS MASKING_EMPNO,
        E.ENAME,
        CONCAT(TO_CHAR(SUBSTR(E.ENAME, 1, 1)), '***') AS MASKING_ENAME
    FROM EMP E
    WHERE LENGTH(E.ENAME) = 5
;

SELECT E.EMPNO, E.ENAME, E.SAL, T.DAY_PAY,
        ROUND(TO_NUMBER(T.DAY_PAY / 8), 1) AS TIME_PAY
    FROM EMP E,
        (SELECT TRUNC(TO_NUMBER(E.SAL / 21.5), 2) AS DAY_PAY 
            FROM EMP E) T
;

SELECT E.EMPNO, E.ENAME, 
        TO_CHAR(E.HIREDATE, 'YYYY-MM-DD'),
        TO_CHAR(NEXT_DAY(ADD_MONTHS(E.HIREDATE, 3) - 1, 'MONDAY'), 'YYYY-MM-DD') AS R_JOB,
        NVL(TO_CHAR(E.COMM), 'N/A') AS COMM
    FROM EMP E
;

SELECT E.EMPNO, E.ENAME, E.MGR,
        CASE 
            WHEN E.MGR IS NULL THEN '0000' 
            WHEN TO_CHAR(SUBSTR(E.MGR, 1, 2)) = '75' THEN '5555'
            WHEN TO_CHAR(SUBSTR(E.MGR, 1, 2)) = '76' THEN '6666'
            WHEN TO_CHAR(SUBSTR(E.MGR, 1, 2)) = '77' THEN '7777'
            WHEN TO_CHAR(SUBSTR(E.MGR, 1, 2)) = '78' THEN '8888'
            ELSE TO_CHAR(E.MGR)
        END AS CHG_MGR
    FROM EMP E
;