SELECT *
    FROM EMP, DEPT
    ORDER BY EMPNO
    ;

SELECT *
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO
    ORDER BY EMPNO
    ;

SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    ORDER BY D.DEPTNO, E.EMPNO
    ;

SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    AND E.SAL >= 3000
    ;

SELECT *
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    ;

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2
    WHERE E1.MGR = E2.EMPNO
    ;

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2
    WHERE E1.MGR = E2.EMPNO(+)
    ORDER BY E1.EMPNO
    ;

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2
    WHERE E1.MGR(+) = E2.EMPNO
    ORDER BY E1.EMPNO
    ;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
        DEPTNO, D.DNAME, D.LOC
    FROM EMP E NATURAL JOIN DEPT D
    ORDER BY DEPTNO, E.EMPNO
    ;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
        DEPTNO, D.DNAME, D.LOC
    FROM EMP E JOIN DEPT D USING (DEPTNO)
    WHERE E.SAL >= 3000
    ORDER BY DEPTNO, E.EMPNO
;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO,
        D.DNAME, D.LOC
    FROM EMP E INNER JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    WHERE E.SAL <= 3000
    ORDER BY DEPTNO, E.EMPNO
    ;

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_NAME
    FROM EMP E1 LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO
    ;

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_NAME
    FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO, MGR_EMPNO
    ;

SELECT E1.EMPNO AS NO1,
        E1.ENAME AS NO2,
        E1.DEPTNO AS NO3
    FROM EMP E1
    ORDER BY NO1
    ;        

SELECT ROWNUM, E.EMPNO, E.ENAME, E.SAL
    FROM (SELECT * FROM EMP ORDER BY SAL DESC) E
    WHERE ROWNUM <= 5
    ;

SELECT ROWNUM, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E
    WHERE ROWNUM <= 5
    ORDER BY SAL DESC
    ;

SELECT ROWNUM, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E
    ORDER BY E.SAL DESC
    OFFSET 0 ROWS FETCH FIRST 5 ROWS ONLY
    ;

SELECT ROWNUM, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E
    ORDER BY E.SAL DESC
    FETCH FIRST 9 ROWS WITH TIES
    ;

SELECT ROWNUM, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E
    ORDER BY E.SAL DESC
    FETCH FIRST 50 PERCENT ROWS ONLY
    ;

SELECT * FROM EMP WHERE SAL >= &SALARY;

SELECT * FROM EMP WHERE JOB = '&JOB_NAME';

SELECT E.EMPNO, E.ENAME, &COL_NAME FROM EMP E;

DEFINE COL_NAME = "COMM";
SELECT E.EMPNO, E.ENAME, &COL_NAME FROM EMP E ORDER BY &COL_NAME;

SELECT * FROM USER_OBJECTS;

SELECT E.DEPTNO,
        GROUPING(E.DEPTNO) AS DG,
        E.JOB,
        GROUPING(E.JOB) AS JG,
        SUM(E.SAL)
    FROM EMP E
    GROUP BY ROLLUP(E.DEPTNO, E.JOB)
    ;
        
SELECT  DECODE(GROUPING_ID(1, DEPTNO, 2, JOB), 7, '전체'
                                                ,15, '전체'
                                                ,DEPTNO) AS DEPTNO,
        DECODE(GROUPING_ID(1, DEPTNO, 2, JOB), 1, '합계'
                                                ,3, '평균'
                                                ,7, '합계'
                                                ,15, '평균'
                                                ,JOB) AS JOB,
        DECODE(GROUPING_ID(1, DEPTNO, 2, JOB), 3, ROUND(AVG(SAL))
                                                ,15, ROUND(AVG(SAL))
                                                ,SUM( SAL)) AS SAL
    FROM EMP
    GROUP BY ROLLUP(1, DEPTNO, 2, JOB);

SELECT EMPNO, ENAME, 
    PREV.SAL AS PREV,
    CURR.SAL AS CURR,
    NEXT.SAL AS NEXT
    FROM (SELECT ROWNUM + 1 AS SEQ,
                SAL
            FROM EMP) PREV
        RIGHT OUTER JOIN (SELECT ROWNUM AS SEQ, 
                                EMPNO, ENAME, SAL
                            FROM EMP) CURR
                        ON PREV.SEQ = CURR.SEQ
        LEFT OUTER JOIN (SELECT ROWNUM - 1 AS SEQ,
                                SAL
                            FROM EMP) NEXT
                        ON CURR.SEQ = NEXT.SEQ
    ORDER BY EMPNO
    ;

SELECT EMPNO, ENAME,
        LAG(SAL) OVER(PARTITION BY DEPTNO ORDER BY SAL) AS PREV_SAL,
        SAL,
        LEAD(SAL) OVER(PARTITION BY DEPTNO ORDER BY SAL) AS NEXT_SAL
    FROM EMP 
    ORDER BY EMPNO
    ;

