SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO,
        D.DNAME, D.LOC
    FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    WHERE E.SAL <= 3000
    ORDER BY E.DEPTNO, E.EMPNO
    ;

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1 
    LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO
    ;

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1 
    RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO
    ;

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1 
    FULL OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO
    ;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
        DEPTNO, D.DNAME, D.LOC
    FROM EMP E JOIN DEPT D USING (DEPTNO)
    WHERE E.SAL >= 3000
    AND E.MGR IS NOT NULL
    ORDER BY DEPTNO, E.EMPNO
    ;

SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    WHERE E.SAL >= 2000
    ORDER BY E.DEPTNO, D.DNAME
    ;

SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO(+)
    AND E.SAL >= 2000
    ORDER BY E.DEPTNO, D.DNAME
    ;

SELECT E.DEPTNO, D.DNAME,
        FLOOR(AVG(E.SAL)) AS AVG_SAL,
        MAX(E.SAL) AS MAX_SAL,
        MIN(E.SAL) AS MIN_SAL,
        COUNT(*) AS CNT
    FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    GROUP BY E.DEPTNO, D.DNAME
    ;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM DEPT D  
    LEFT OUTER JOIN EMP E ON (E.DEPTNO = D.DEPTNO) 
    ORDER BY D.DEPTNO, D.DNAME, E.ENAME
    ;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM DEPT D, EMP E
    WHERE D.DEPTNO = E.DEPTNO(+)
    ORDER BY D.DEPTNO, D.DNAME, E.ENAME
    ;

SELECT D.DEPTNO, D.DNAME, 
        E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL,
        E1.DEPTNO AS DEPTNO_1,
        CASE 
            WHEN E1.SAL > 3000 THEN 3001
            WHEN E1.SAL > 2000 THEN 2001
            WHEN E1.SAL > 1400 THEN 1401
            WHEN E1.SAL > 1200 THEN 1201
            WHEN E1.SAL > 700 THEN 700 
        END AS LOSAL,
        CASE 
            WHEN E1.SAL > 3000 THEN 9999
            WHEN E1.SAL > 2000 THEN 3000
            WHEN E1.SAL > 1400 THEN 2000
            WHEN E1.SAL > 1200 THEN 1400
            WHEN E1.SAL > 700 THEN 1200
        END AS HISAL,
        CASE 
            WHEN E1.SAL > 3000 THEN 5
            WHEN E1.SAL > 2000 THEN 4
            WHEN E1.SAL > 1400 THEN 3
            WHEN E1.SAL > 1200 THEN 2
            WHEN E1.SAL > 700 THEN 1
        END AS GRADE,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1
    LEFT OUTER JOIN DEPT D ON D.DEPTNO = E1.DEPTNO
    LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY D.DEPTNO, D.DNAME, E1.EMPNO, E1.ENAME
    ;

SELECT D.DEPTNO, D.DNAME, 
        E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL,
        E1.DEPTNO AS DEPTNO_1,
        CASE 
            WHEN E1.SAL > 3000 THEN 3001
            WHEN E1.SAL > 2000 THEN 2001
            WHEN E1.SAL > 1400 THEN 1401
            WHEN E1.SAL > 1200 THEN 1201
            WHEN E1.SAL > 700 THEN 700 
        END AS LOSAL,
        CASE 
            WHEN E1.SAL > 3000 THEN 9999
            WHEN E1.SAL > 2000 THEN 3000
            WHEN E1.SAL > 1400 THEN 2000
            WHEN E1.SAL > 1200 THEN 1400
            WHEN E1.SAL > 700 THEN 1200
        END AS HISAL,
        CASE 
            WHEN E1.SAL > 3000 THEN 5
            WHEN E1.SAL > 2000 THEN 4
            WHEN E1.SAL > 1400 THEN 3
            WHEN E1.SAL > 1200 THEN 2
            WHEN E1.SAL > 700 THEN 1
        END AS GRADE,
        NTILE(5) OVER (ORDER BY E1.SAL ASC) AS GRADE_1,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1
    LEFT OUTER JOIN DEPT D ON D.DEPTNO = E1.DEPTNO
    LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY D.DEPTNO, D.DNAME, E1.EMPNO, E1.ENAME
    ;

SELECT E1.DEPTNO, D.DNAME,
        E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL, 
        E1.DEPTNO AS DEPTNO_1
        --DECODE(GRADE.)--D.LOSAL,
        --AS HISAL,
        --AS GRADE,
        --E2.EMPNO AS MGR_EMPNO,
        --E2.ENAME AS MGR_ENAME
    FROM EMP E1
    LEFT OUTER JOIN DEPT D ON (E1.EMPNO = D.DEPTNO)
    LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY D.DEPTNO, D.DNAME, E1.EMPNO, E1.ENAME
    ;

SELECT * FROM EMP E;
SELECT * FROM DEPT D;


SELECT COUNT(DISTINCT E.MGR) 
    FROM EMP E
    ;

SELECT ABS(-500), ABS(500) FROM DUAL;

SELECT SIGN(-500), SIGN(500), SIGN(0) FROM DUAL;

SELECT POWER(2, 10) FROM DUAL;

SELECT MOD(9, 2), MOD(8, 3) FROM DUAL;

SELECT SQRT(16), SQRT(15) FROM DUAL;

SELECT CEIL(123.456) FROM DUAL;

SELECT FLOOR(123.456) FROM DUAL;

SELECT ROUND(0.515), ROUND(0.145, 1), ROUND(0.142, 2) FROM DUAL;

SELECT TRUNC(1234.5678, -1) AS TRUNC1,
       TRUNC(1234.5678, 0) AS TRUNC2,
        TRUNC(1234.5678, 1) AS TRUNC3,
        TRUNC(1234.5678, 2) AS TRUNC4
    FROM DUAL;

SELECT EMPNO, ENAME, 
        LAG(SAL) OVER(ORDER BY EMPNO) AS PREV_SAL, 
        SAL,
        LEAD(SAL) OVER(ORDER BY EMPNO) AS NEXT_SAL
    FROM EMP
    ORDER BY EMPNO
    ;

SELECT EMPNO, ENAME, 
        LAG(SAL, 2) OVER(ORDER BY EMPNO) AS PREV_SAL, 
        SAL,
        LEAD(SAL, 2) OVER(ORDER BY EMPNO) AS NEXT_SAL
    FROM EMP
    ORDER BY EMPNO
    ;

SELECT EMPNO, ENAME, 
        LAG(SAL, 2, 0) OVER(ORDER BY EMPNO) AS PREV_SAL, 
        SAL,
        LEAD(SAL, 2, 0) OVER(ORDER BY EMPNO) AS NEXT_SAL
    FROM EMP
    ORDER BY EMPNO
    ;

SELECT EMPNO, ENAME, SAL, DEPTNO, ROW_NUMBER() OVER(ORDER BY SAL DESC) AS RNK
    FROM EMP
    ;

SELECT EMPNO, ENAME, SAL, DEPTNO,
        ROW_NUMBER() OVER(ORDER BY SAL DESC) AS RN_RANK,
        RANK() OVER(ORDER BY SAL DESC) AS RANK,
        DENSE_RANK() OVER(ORDER BY SAL DESC) AS D_RANK
    FROM EMP
    ;



