SELECT DEPTNO, EMPNO, ENAME, SAL
        ,SUM(SAL) OVER(
            ORDER BY DEPTNO
            ROWS BETWEEN UNBOUNDED PRECEDING
            AND CURRENT ROW
        ) AS SUM_SAL
    FROM EMP
    ;

SELECT DEPTNO, EMPNO, ENAME, SAL
        ,SUM(SAL) OVER(
            ORDER BY DEPTNO
            ROWS UNBOUNDED PRECEDING
        ) AS SUM_SAL
    FROM EMP
    ;

SELECT DEPTNO, EMPNO, ENAME, SAL,
        ROUND(AVG(SAL) OVER(
            ORDER BY SAL
            RANGE BETWEEN 1000 PRECEDING
            AND 1000 FOLLOWING
        )) AS AVG_SAL
    FROM EMP
    ;

SELECT EMPNO, ENAME, SAL, DEPTNO, 
        ROW_NUMBER() OVER(ORDER BY SAL DESC) AS RN_RANK, 
        RANK() OVER(ORDER BY SAL DESC) AS RANK, 
        DENSE_RANK() OVER(ORDER BY SAL DESC) AS D_RANK
    FROM EMP
    ;

SELECT EMPNO, ENAME, SAL, DEPTNO, 
        RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS RNK
    FROM EMP
    ;

SELECT RANK(2975) WITHIN GROUP (ORDER BY SAL DESC) AS RNK
        ,DENSE_RANK(2975) WITHIN GROUP (ORDER BY SAL DESC) AS D_RNK
    FROM EMP
    ;


