SELECT E.EMPNO, E.ENAME, D.DNAME, 
        TO_CHAR(E.HIREDATE, 'YYYY-MM-DD'),
        D.LOC, E.SAL, G.GRADE
    FROM EMP E
    INNER JOIN DEPT D ON (D.DEPTNO = E.DEPTNO)
    INNER JOIN SALGRADE G ON E.SAL BETWEEN G.LOSAL AND G.HISAL
    WHERE E.SAL > (SELECT AVG(SAL) FROM EMP)
    ORDER BY E.SAL DESC, E.EMPNO
    ;

SELECT E.EMPNO, E.ENAME, E.JOB, E.DEPTNO,
        D.DNAME, D.LOC
    FROM EMP E
    INNER JOIN DEPT D ON (D.DEPTNO = E.DEPTNO)
    WHERE E.DEPTNO = 10
    AND E.JOB NOT IN (SELECT DISTINCT T.JOB FROM EMP T WHERE T.DEPTNO = 30)
    ;

SELECT E.EMPNO, E.ENAME, E.SAL, G.GRADE
    FROM EMP E
    INNER JOIN SALGRADE G ON E.SAL BETWEEN G.LOSAL AND G.HISAL
    WHERE E.SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN')
    ;

CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;

DROP TABLE DEPT_TEMP;

CREATE TABLE EMP_TEMP10
    AS SELECT * FROM EMP;

DROP TABLE EMP_TEMP10;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
        VALUES (50, 'DATABASE', 'SEOUL');

INSERT INTO DEPT_TEMP
        VALUES (60, 'NETWORK', 'BUSAN');

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
        VALUES (70, 'WEB', NULL);

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
        VALUES (80, 'MOBILE', '');

INSERT INTO DEPT_TEMP (DEPTNO, LOC)
        VALUES (90, 'INCHEON');

CREATE TABLE EMP_TEMP
    AS SELECT * FROM EMP WHERE 1 <> 1;

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
        VALUES (9999, '박인성', 'STUDENT', NULL, TO_DATE('1999/12/26', 'YYYY/MM/DD'), 5000, 1000, 10);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
        VALUES (1111, '박지성', 'TEACHER', NULL, TO_DATE('1998-11-26', 'YYYY-MM-DD'), 4000, NULL, 20);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
        VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
        FROM EMP E, SALGRADE S
        WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
        AND S.GRADE = 1
        ;

MERGE INTO EMP_TEMP T
    USING EMP E ON (T.EMPNO = E.EMPNO)
    WHEN MATCHED THEN 
        UPDATE SET T.SAL = 4000
        WHERE E.DEPTNO = 20
        ;

MERGE INTO EMP_TEMP T
    USING EMP E ON (T.EMPNO = E.EMPNO)
    WHEN MATCHED THEN
        UPDATE SET T.SAL = E.SAL
        DELETE WHERE E.DEPTNO = 20
        ;

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (1234, 'Jane', 'STUDENT', NULL, SYSDATE, 2500, NULL, 40)
    RETURNING ENAME INTO :new_ENAME
    ;

CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;

UPDATE EMP_TEMP
    SET COMM = 50
    WHERE SAL <= 2500
    ;

SELECT * FROM EMP_TEMP;

UPDATE DEPT_TEMP
    SET DNAME = 'DATABASE',
        LOC = 'SEOUL'
    WHERE DEPTNO = 40;

UPDATE DEPT_TEMP
    SET (DNAME, LOC) = (SELECT DNAME, LOC
                            FROM DEPT
                            WHERE DEPTNO = 40)
    WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP;

SELECT * FROM ALL_TABLES
    WHERE OWNER = 'SCOTT';


SELECT *
  FROM ALL_COL_COMMENTS
 WHERE OWNER = 'SCOTT'
 ;

PRINT new_ENAME;

ROLLBACK;
COMMIT;
DESC EMP_TEMP;

SELECT * FROM EMP_TEMP T;

SELECT * FROM EMP_TEMP T
    INNER JOIN EMP E ON (T.EMPNO = E.EMPNO);

SELECT * FROM DEPT_TEMP;

SELECT * FROM SALGRADE;

SELECT * FROM EMP;

SELECT * 
    FROM ALL_TAB_COMMENTS
    --WHERE TABLE_TYPE = 'TABLE'
    ;

SELECT * FROM TABS;