SELECT * 
    FROM EMP A, EMP B
    ;

UPDATE CHAP10HW_EMP T
    SET T.DEPTNO = 70
    WHERE T.SAL >= (SELECT AVG(E.SAL) FROM CHAP10HW_EMP E WHERE E.DEPTNO = 50)
    ;

SELECT * FROM CHAP10HW_EMP T ORDER BY T.DEPTNO;

COMMIT;

UPDATE CHAP10HW_EMP T
    SET T.SAL = (T.SAL * 1.1),
        T.DEPTNO = 80
    WHERE T.HIREDATE >= (SELECT MIN(A.HIREDATE)
                            FROM CHAP10HW_EMP A WHERE A.DEPTNO = 60)
                            ;

SELECT * 
    FROM CHAP10HW_EMP T 
    WHERE T.HIREDATE >= (SELECT MIN(A.HIREDATE)
                            FROM CHAP10HW_EMP A WHERE A.DEPTNO = 60)
                            ;
    
ROLLBACK;

DELETE FROM CHAP10HW_EMP
    WHERE EMPNO IN (SELECT T.EMPNO
                        FROM CHAP10HW_EMP T
                        INNER JOIN SALGRADE A ON (T.SAL BETWEEN A.LOSAL AND A.HISAL)
                        WHERE A.GRADE = 5)
    ;

SELECT * FROM CHAP10HW_EMP;

SELECT T.ENAME
    FROM CHAP10HW_EMP T
    INNER JOIN SALGRADE A ON (T.SAL BETWEEN A.LOSAL AND A.HISAL)
    WHERE A.GRADE = 5;

SELECT * FROM SALGRADE;

CREATE TABLE DEPT_TCL
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;

DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

INSERT INTO DEPT_TCL VALUES(50, 'NETWORK', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 20;

DELETE FROM DEPT_TCL WHERE DEPTNO = 40;



SELECT * FROM DEPT_TCL;
ROLLBACK;
COMMIT;