SELECT * FROM V$SESSION;

CREATE TABLE EMP_DDL (
    EMPNO       NUMBER(4),
    ENAME       VARCHAR2(10),
    JOB         VARCHAR(9),
    MGR         NUMBER(4),
    HIREDATE    DATE,
    SAL         NUMBER(7,2),
    COMM        NUMBER(7,2),
    DEPTNO      NUMBER(2)
);

CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;

CREATE TABLE EMP_DDL_30
    AS SELECT * FROM EMP WHERE DEPTNO =30;

CREATE TABLE EMPDEPT_DDL
    AS SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
                E.SAL, E.COMM, E.DEPTNO, D.DNAME, D.LOC
            FROM EMP E, DEPT D
            WHERE 1 <> 1;

CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;

ALTER TABLE EMP_ALTER
    ADD HP VARCHAR2(20);

ALTER TABLE EMP_ALTER
    RENAME COLUMN HP TO TEL;

ALTER TABLE EMP_ALTER
    MODIFY EMPNO NUMBER(5);

ALTER TABLE EMP_ALTER
    DROP COLUMN TEL;

RENAME EMP_ALTER TO EMP_RENAME;

TRUNCATE TABLE EMP_RENAME;

CREATE TABLE EMP_HW (
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2)
    );

ALTER TABLE EMP_HW 
    ADD BIGO VARCHAR2(20);

ALTER TABLE EMP_HW 
    MODIFY BIGO VARCHAR2(30);

ALTER TABLE EMP_HW
    RENAME COLUMN BIGO TO REMARK;

SELECT * FROM EMP_HW;

CREATE TABLE EMP_HW 
   AS SELECT * FROM EMP 
;

ALTER TABLE EMP_HW
    ADD REMARK VARCHAR2(30);

SELECT * FROM EMP_HW;

--DROP TABLE EMP_HW;

COMMIT;

DESC DEPT_DDL;
DESC EMP_DDL;

SELECT * FROM EMP_DDL;
SELECT * FROM DEPT_DDL;
SELECT * FROM EMP_DDL_30;
SELECT * FROM EMPDEPT_DDL;
SELECT * FROM EMP_ALTER;
SELECT * FROM EMP_RENAME;


-----------------------------------------

SELECT * FROM DICT;

SELECT * FROM DICTIONARY;

SELECT * FROM USER_TABLES;

SELECT * FROM ALL_TABLES;

SELECT * FROM USER_INDEXES;

SELECT * FROM USER_IND_COLUMNS;

CREATE INDEX IDX_EMP_SAL
    ON EMP(SAL);

DROP INDEX IDX_EMP_SAL;

SELECT * FROM USER_IND_COLUMNS;

CREATE OR REPLACE VIEW VW_EMP20
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO
            FROM EMP
            WHERE DEPTNO = 20)
            ;

SELECT * FROM USER_VIEWS;

SELECT * FROM VW_EMP20;

DROP VIEW VW_EMP20;

SELECT ROWNUM, E.* 
    FROM EMP E
    ORDER BY SAL DESC;

SELECT ROWNUM, T.*
    FROM (SELECT * 
            FROM EMP
            ORDER BY SAL DESC) T
    ;

WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM, E.*
    FROM E;

SELECT ROWNUM, E.*
    FROM (SELECT *
            FROM EMP E
            ORDER BY SAL DESC) E
    WHERE ROWNUM <= 3
    ;

WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM, E.*
    FROM E
    WHERE ROWNUM <= 3
    ;    

CREATE TABLE DEPT_SEQUENCE 
    AS SELECT * FROM DEPT WHERE 1 <> 1;

SELECT * FROM DEPT_SEQUENCE;

CREATE SEQUENCE DEPT_S
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 2
    ;

INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
    VALUES (DEPT_S.NEXTVAL, 'DATABASE', 'SEOUL')
    ;

SELECT DEPT_S.CURRVAL FROM DUAL;

INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
    VALUES (DEPT_S.NEXTVAL, 'DATAB', 'SEOUL')
    ;

ALTER SEQUENCE DEPT_S
    INCREMENT BY 3
    MAXVALUE 99
    CYCLE;

DROP SEQUENCE DEPT_S;

SELECT * FROM USER_SEQUENCES;

CREATE PUBLIC SYNONYM E
    FOR SCOTT.EMP
    ;

SELECT * FROM E;

DROP SYNONYM E;

SELECT * FROM USER_SYNONYMS;

SELECT * FROM DEPT_SEQUENCE;

GRANT CREATE VIEW TO SCOTT;
GRANT CREATE SYNONYM TO SCOTT;
GRANT CREATE PUBLIC SYNONYM TO SCOTT;



------------------------------------------------

CREATE TABLE EMPIDX 
    AS SELECT * 
        FROM EMP
    ;

CREATE INDEX IDX_EMPIDX_EMPNO
    ON EMPIDX(EMPNO)
    ;

SELECT * FROM USER_INDEXES;


CREATE OR REPLACE VIEW EMPIDX_OVER15K
    AS (SELECT E.EMPNO, E.ENAME, E.JOB, E.DEPTNO, E.SAL, 
                NVL2(E.COMM, 'O', 'X') AS COMM
            FROM EMPIDX E)
        ;

SELECT * FROM EMPIDX_OVER15K;

SELECT * FROM EMPIDX;

CREATE TABLE DEPTSEQ
    AS SELECT * FROM DEPT
    ;

CREATE SEQUENCE DEPTSEQ_S
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE
    NOCACHE 
    ;

SELECT * FROM USER_SEQUENCES;

INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC)
    VALUES (DEPTSEQ_S.NEXTVAL, 'DATABASE', 'SEOUL')
    ;

INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC)
    VALUES (DEPTSEQ_S.NEXTVAL, 'WEB', 'BUSAN')
    ;

INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC)
    VALUES (DEPTSEQ_S.NEXTVAL, 'MOBILE', 'ILSAN')
    ;

DELETE FROM DEPTSEQ
WHERE DEPTNO = 1;

SELECT * FROM DEPTSEQ;