ALTER user SCOTT IDENTIFIED BY tiger;

GRANT SELECT ON ALL_TAB_COLUMNS TO SCOTT;
GRANT SELECT ANY TABLE TO SCOTT;
GRANT DBA TO SCOTT;

CREATE TABLE TABLE_NOTNULL2 (
    LOGIN_ID    VARCHAR(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL,
    LOGIN_PWD   VARCHAR(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
    TEL         VARCHAR(20)
    );

INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD)
    VALUES ('TEST_ID_01', '1234');

ALTER TABLE TABLE_NOTNULL
    MODIFY(TEL NOT NULL);

ALTER TABLE TABLE_NOTNULL
    MODIFY(LOGIN_ID CONSTRAINT TBLNN_LGNID_NN NOT NULL);

ALTER TABLE TABLE_NOTNULL
    DROP CONSTRAINT SYS_C007494;

UPDATE TABLE_NOTNULL T
    SET T.TEL = '010-1234-5678'
    WHERE T.LOGIN_ID = 'TEST_ID_01'
    ;

ALTER TABLE TABLE_NOTNULL2 
    MODIFY(TEL CONSTRAINT TBLNN2_TEL_NN NOT NULL);

ALTER TABLE TABLE_NOTNULL2
    RENAME CONSTRAINT TBLNN_TEL_NN TO TBLNN2_TEL_NN;

CREATE TABLE TABLE_PK2(
    LOGIN_ID    VARCHAR(20) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY,
    LOGIN_PWD   VARCHAR(20) CONSTRAINT TBLPK2_LGNPW_NN NOT NULL,
    TEL         VARCHAR(20)
    );

INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_01', 'PWD02', '010-2345-6789');

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_OWNER, R_CONSTRAINT_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME IN ('EMP', 'DEPT');

DROP TABLE DEPT_FK;

CREATE TABLE DEPT_FK(
    DEPTNO  NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME   VARCHAR2(14),
    LOC     VARCHAR2(13)
);

CREATE TABLE EMP_FK(
    EMPNO       NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME       VARCHAR2(10),
    JOB         VARCHAR2(9),
    MGR         NUMBER(4),
    HIREDATE    DATE,
    SAL         NUMBER(7, 2),
    COMM        NUMBER(7, 2),
    DEPTNO      NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)    
    );

INSERT INTO DEPT_FK
    VALUES(10, 'TEST_DNAME', 'TEST_LOC');

INSERT INTO EMP_FK
    VALUES(9999, 'TEST_NMAME', 'TEST_JOB', NULL, TO_DATE('1999/12/26', 'YYYY-MM-DD'), 3000, NULL, 10);

DELETE FROM DEPT_RK WHERE DEPTNO = 10;

CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO) ON DELETE CASCADE;

CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO) ON DELETE SET NULL;

ALTER TABLE EMP_FK DROP CONSTRAINT EMPFK_DEPTNO_FK;

ALTER TABLE EMP_FK 
    ADD CONSTRAINT EMPFK_DEPTNO_FK FOREIGN KEY(DEPTNO)
    REFERENCES DEPT_FK(DEPTNO) ON DELETE SET NULL
    ;

ALTER TABLE EMP_FK
    MODIFY(DEPTNO CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO) ON DELETE CASCADE);

DELETE FROM DEPT_FK WHERE DEPTNO = 10;

CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID    VARCHAR2(20) CONSTRAINT TBLCK2_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD   VARCHAR2(20) DEFAULT '1234',
    TEL         VARCHAR2(20)
);

INSERT INTO TABLE_DEFAULT VALUES ('TEST_ID', NULL, '010-1234-5678');

INSERT INTO TABLE_DEFAULT(LOGIN_ID, TEL) VALUES ('TEST_ID2', '010-1234-5678');

ALTER TABLE TABLE_PK2 DISABLE NOVALIDATE CONSTRAINT TBLPK2_LGNPW_NN;

SELECT * FROM EMP_FK;
SELECT * FROM DEPT_FK;
SELECT * FROM TABLE_DEFAULT;
SELECT * FROM USER_CONSTRAINTS T
    --WHERE T.TABLE_NAME LIKE 'TABLE_D%'
    ;
SELECT * FROM USER_INDEXES WHERE TABLE_NAME LIKE 'TABLE_PK%';
DESC TABLE_DEFAULT;

SELECT * FROM ALL_TAB_COLUMNS;
select * from user_tables;

COMMIT;
ROLLBACK;