CREATE TABLE DEPT_CONST(
    DEPTNO      NUMBER(2)       CONSTRAINT DEPTC0NST_DEPTNO_PK  PRIMARY KEY,
    DNAME       VARCHAR2(14)    CONSTRAINT DEPTCONST_DNAME_UNQ  UNIQUE,
    LOC         VARCHAR2(13)    CONSTRAINT DEPTCONST_LOC_NN     NOT NULL
);

CREATE TABLE EMP_CONST(
    EMPNO       NUMBER(4)       CONSTRAINT EMPC0NST_EMPNO_PK    PRIMARY KEY,
    ENAME       VARCHAR2(10)    CONSTRAINT EMPCONST_ENAME_NN    NOT NULL,
    JOB         VARCHAR2(9),
    TEL         VARCHAR2(20)    CONSTRAINT EMPCONST_TEL_UNQ     UNIQUE,
    HIREDATE    DATE,
    SAL         NUMBER(7, 2)    CONSTRAINT EMPC0NST_SAL_CHK     CHECK (SAL >=1000 AND SAL <= 9999),
    COMM        NUMBER(7, 2),
    DEPTNO      NUMBER(2)       CONSTRAINT EMPCONST_DEPTNO_FK   REFERENCES DEPT_CONST(DEPTNO)
);


DESC DEPT_CONST;
DESC EMP_CONST;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'EMP_CONST';

CREATE USER USER_NAME IDENTIFIED BY PASSWORD DEFAULT TABLESPACE TABLESPACE_NAME
TEMPORARY TABLESPACE TABLESPACE_NAME QUOTA TABLESPACE_SIZE ON TABLESPACE_NAME
PROFILE PROFILE_NAME PASSWORD EXPIRE ACCOUNT (LOCK/UNLOCK);

SELECT * FROM ALL_USERS;
SELECT * FROM DBA_USERS;

SELECT * FROM DBA_OBJECTS WHERE OWNER = 'SCOTT';

select * from user_mviews;
select * from v$controlfile;
select * from v$parameter --where name='control_files'
;

SELECT * FROM V$SESSION WHERE SCHEMANAME = 'SCOTT';

CREATE ROLE ROLESTUDY;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO ROLESTUDY;

CREATE USER ORCLSTUDY;

GRANT ROLESTUDY TO ORCLSTUDY;

SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;

ALTER USER ORCLSTUDY IDENTIFIED BY "1234";

CREATE USER PREV_HW IDENTIFIED BY "1234";

GRANT CREATE SESSION TO PREV_HW;

GRANT SELECT ON SCOTT.EMP TO PREV_HW;
GRANT SELECT ON SCOTT.DEPT TO PREV_HW;
GRANT SELECT ON SCOTT.SALGRADE TO PREV_HW;

SELECT * FROM SCOTT.EMP;
SELECT * FROM SCOTT.DEPT;
SELECT * FROM SCOTT.SALGRADE;

REVOKE SELECT ON SCOTT.EMP FROM PREV_HW;

COMMIT;

SELECT * FROM DBA_TAB_PRIVS WHERE TABLE_NAME='EMP';
SELECT * FROM DBA_SYNONYMS WHERE TABLE_NAME = 'EMP';


SELECT * FROM DBA_POLICIES WHERE OBJECT_NAME = 'EMP';
