SET SERVEROUTPUT ON; -- PL/SQL 결과를 화면에 표시
BEGIN
    DBMS_OUTPUT.PUT_LINE('HELLO, PL/SQL!');
END;
/ --명령프롬프트에서 할 때 '/' 필수

DECLARE
    V_EMPNO NUMBER(4) := 7788;
    V_ENAME VARCHAR2(10);

BEGIN
    V_ENAME := 'SCOTT';    
    DBMS_OUTPUT.PUT_LINE('V_EMPNO : ' || V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('V_ENAME : ' || V_ENAME);    
END;
/


-- 상수에 값 대입 후 출력
DECLARE
    V_TAX CONSTANT NUMBER(1) := 3;

BEGIN
    DBMS_OUTPUT.PUT_LINE('V_TAX : ' || V_TAX);
END;
/


-- 변수에 기본값 설정 후 출력
DECLARE
    V_DEPTNO NUMBER(2) DEFAULT 10;

BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;
/


-- 변수 NOT NULL 및 기본 값을 설정 후 출력
DECLARE
    V_DEPTNO NUMBER(2) NOT NULL DEFAULT 10;

BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;
/


-- 참조행의 변수에 값을 대입 후 출력
DECLARE
    V_DEPTNO DEPT.DEPTNO%TYPE := 50;

BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;
/


-- 참조행의 변수에 값을 대입 후 출력
DECLARE
    V_DEPT_ROW DEPT%ROWTYPE;

BEGIN
    SELECT DEPTNO, DNAME, LOC
        INTO V_DEPT_ROW
        FROM DEPT
        WHERE DEPTNO = 40;
    DBMS_OUTPUT.PUT_LINE('DEPTNO : ' || V_DEPT_ROW.DEPTNO);
    DBMS_OUTPUT.PUT_LINE('DNAME : ' || V_DEPT_ROW.DNAME);
    DBMS_OUTPUT.PUT_LINE('LOC : ' || V_DEPT_ROW.LOC);
END;
/

CREATE TABLE TEST_DATE (
        LOC_DATE VARCHAR2(20),
        LOC_DATE2 NUMBER(20),
        LOC_DATE3 DATE
    );

SELECT * FROM TEST_DATE;

SELECT REGEXP_REPLACE(LOC_DATE3, '([[:digit:]]{4})(\d{2})(\d{2})', '\1-\2-\3') AS POST_DATE 
    FROM TEST_DATE;

INSERT INTO TEST_DATE 
    VALUES ('20150201', 20150304, TO_DATE('2015-04-19', 'YYYY-MM-DD'));

SELECT ST_ASTEXT('09UE012')
    FROM DUAL;

SELECT * FROM USER_LIBRARIES;